# Generated by Django 5.1.7 on 2025-03-07 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.PositiveIntegerField()),
                ('truck_number', models.CharField(max_length=50)),
                ('carrier_name', models.CharField(max_length=255)),
                ('main_office_address', models.CharField(max_length=255)),
                ('driver_signature', models.CharField(max_length=255)),
                ('co_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_base', models.CharField(max_length=50)),
                ('remarks', models.JSONField(blank=True, default=list)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('shipping_document', models.CharField(blank=True, max_length=255, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
