# Generated by Django 5.1.7 on 2025-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_logentry_time_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='total_miles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
